### ISSUE TITLE
Faster Playlist Validation

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTubeConverter#310]
Thread start from: https://github.com/NickvisionApps/TubeConverter/issues/129#issuecomment-1570375362

**Comment by nlogozzo** [comment]
I found a way to drastically speed up playlist validation, so this preference is no longer needed!

**Comment by nlogozzo** [comment]
@quazar-omega  
See: https://github.com/NickvisionApps/TubeConverter/pull/335#issuecomment-1581706839
Look at that speed!

**Comment by quazar-omega** [comment]
Wow, that's insane, great job! What was the secret sauce?

**Comment by quazar-omega** [comment]
Very nice!

**Comment by nlogozzo** [comment]
Hopefully we'll have beta2 out by tonight for you to use

**Comment by quazar-omega** [comment]
Ok, I'll make sure to test it then!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2

**Comment by quazar-omega** [comment]
Got it!  
Tested on [this album](https://music.youtube.com/playlist?list=OLAK5uy_lIZdM2pq9c1fjP33qpiibhg2qg4i0J2B8).
Options:
- download with aria2
- crop thumbnail

<details>
<summary>
I got an exception in the terminal:
</summary>

```
Python.Runtime.PythonException: write to closed file                                                                                                                                                                                       
  File "/app/lib/python3.10/site-packages/yt_dlp/utils.py", line 2071, in write_string
    buffer.write(s.encode(enc, 'ignore') if enc else s)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 856, in _write_string
    write_string(message, out=out, encoding=self.params.get('encoding'))
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 885, in to_stderr
    self._write_string(f'{self._bidi_workaround(message)}\n', self._out_files.error, only_once=only_once)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 935, in trouble
    self.to_stderr(message)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1539, in wrapper
    self.report_error(str(e), tb=encode_compat_str(traceback.format_exc()))
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure, CallSite, Object, List`1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at NickvisionTubeConverter.Shared.Models.Download.<>c__DisplayClass66_0.<Start>b__0() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Models/Download.cs:line 335
```
</details>

<details>
<summary>
And one element wasn't downloaded, though the log doesn't seem to show errors?
</summary>

```
[youtube] Extracting URL: https://music.youtube.com/watch?v=hM3gEC_VnvE
[youtube] Extracting URL: https://music.youtube.com/watch?v=Py7Mo0pf4w4
[youtube] hM3gEC_VnvE: Downloading webpage
[youtube] Py7Mo0pf4w4: Downloading webpage
[youtube] hM3gEC_VnvE: Downloading android player API JSON
[youtube] Py7Mo0pf4w4: Downloading android player API JSON
[youtube] hM3gEC_VnvE: Downloading android music player API JSON
[youtube] Py7Mo0pf4w4: Downloading android music player API JSON
[youtube] hM3gEC_VnvE: Downloading web music client config
[youtube] Py7Mo0pf4w4: Downloading web music client config
[youtube] hM3gEC_VnvE: Downloading player 8c7583ff
[youtube] Py7Mo0pf4w4: Downloading player 8c7583ff
[youtube] Py7Mo0pf4w4: Downloading web music player API JSON
[youtube] hM3gEC_VnvE: Downloading web music player API JSON
[info] hM3gEC_VnvE: Downloading 1 format(s): 251
[info] Py7Mo0pf4w4: Downloading 1 format(s): 251
[info] Downloading video thumbnail 47 ...
[info] Downloading video thumbnail 47 ...
[info] Writing video thumbnail 47 to: /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.webp
[info] Writing video thumbnail 47 to: /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/b9d974e5-6fa8-4c26-901c-465a7f9bc5b6/b9d974e5-6fa8-4c26-901c-465a7f9bc5b6.webp
[dashsegments] Total fragments: 1
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.webm
[dashsegments] Total fragments: 1
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/b9d974e5-6fa8-4c26-901c-465a7f9bc5b6/b9d974e5-6fa8-4c26-901c-465a7f9bc5b6.webm

[download] 100% of    1.14MiB in 00:00:00 at 1.28MiB/s
[ExtractAudio] Destination: /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.opus
Deleting original file /home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.webm (pass -k to keep)
[MetadataFromField] Parsed meta_comment from '': ''
[MetadataFromField] Parsed meta_description from '': ''
[MetadataFromField] Parsed meta_synopsis from '': ''
[TCMetadata] Adding metadata to "/home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.opus"
[ThumbnailsConvertor] Converting thumbnail "/home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.webp" to png
[TCEmbedThumbnail] mutagen: Adding thumbnail to "/home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.opus"
[MoveFiles] Moving file "/home/amusing-dove/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/e94c85a9-79e1-453d-bda0-372c21a96a8c/e94c85a9-79e1-453d-bda0-372c21a96a8c.opus" to "/run/user/1000/doc/329a9939/Islands of the lost and forgotten/e94c85a9-79e1-453d-bda0-372c21a96a8c.opus"
```
</details>

Retrying the download worked though.
This is great, I also noticed there a lot of other interesting features, you're really killing it!

**Comment by nlogozzo** [comment]
Thank you :))
I'll see if I can reproduce the issue ...

**Comment by nlogozzo** [comment]
> Retrying that single failed download worked though.

@fsobolev Maybe it would be good to implement #343 where if a download fails we retry it once, if it fails again the user will have to initiate further retries...
