### ISSUE TITLE
Flatpak version fails to download

### ISSUE THREAD

**Issue by brunoais** [nlogozzo/NickvisionTubeConverter#76]
I don't know anything else about this problem. The flatpak version doesn't download videos.

```
URL: URL: https://www.youtube.com/watch?v=OH5-Y37s88o
Path: /run/user/1000/doc/d602fb70/tmp/HP gives up, Flathub payments, companies using FOSS wrong: Linux & Open Source News.mp4
Quality: 0
[generic] Extracting URL: URL: https://www.youtube.com/watch?v=OH5-Y37s88o
[generic] watch?v=OH5-Y37s88o: Downloading webpage

[Error] Unable to download video
```

**Comment by nlogozzo** [comment]
What version of Tube Converter are you running?

**Comment by fsobolev** [comment]
I can't confirm this, I successfully downloaded the video both with stable flatpak (old C++ version) and current master.

> What version of Tube Converter are you running?

Looking at the first 3 lines of provided logs, it's old version.

**Comment by fsobolev** [comment]
@brunoais Please try [latest beta](https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-beta2) (you can download flatpak file from the release page or install beta version from Flathub Beta repository). If the problem persists, please try downloading a video using [yt-dlp](https://github.com/yt-dlp/yt-dlp).

**Comment by brunoais** [comment]
Crash (log slightly modified to hide my PC paths):
```
Unhandled exception. 
(NickvisionTubeConverter.GNOME:2): Gtk-WARNING **: 13:13:35.306: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well
Python.Runtime.PythonException: [Errno 2] No such file or directory: '/home/brunoais/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/output.log'
  File "<string>", line 1, in <module>
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PythonException.ThrowIfIsNull(NewReference& ob)
   at Python.Runtime.PythonEngine.RunString(String code, BorrowedReference globals, BorrowedReference locals, RunFlagType flag)
   at Python.Runtime.PythonEngine.Eval(String code, PyDict globals, PyObject locals)
   at NickvisionTubeConverter.Shared.Helpers.PythonExtensions.SetConsoleOutputFilePath(String path) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Helpers/PythonExtensions.cs:line 20
   at NickvisionTubeConverter.Shared.Models.Download.GetIsValidVideoUrlAsync(String url) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Models/Download.cs:line 132
   at NickvisionTubeConverter.Shared.Controllers.AddDownloadDialogController.UpdateDownloadAsync(String videoUrl, MediaFileType mediaFileType, String savePath, Quality quality, Subtitle subtitles) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Controllers/AddDownloadDialogController.cs:line 101
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.ValidateAsync() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 132
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.<>c__DisplayClass13_0.<<-ctor>b__1>d.MoveNext() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 58
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I'll created the directory and tried again.
I tried to assign a directory and the file picker locked up. So I force-closed it.
Now the program is locking up when trying to use the file picker and not getting it working. I don't think this is a TubeConverter issue. I'll give news after I fix this

**Comment by brunoais** [comment]
Version `2023.3.0-beta2` works. It also works for the subtitles.
The only thing I'd be eager for would be converting the subtitles file which represents the chapters into chapters themselves but that's a feature request and not a bug.

I suppose the fix will go to flathub at some point.
What should we do about this issue?

**Comment by fsobolev** [comment]
> The only thing I'd be eager for would be converting the subtitles file which represents the chapters into chapters themselves but that's a feature request and not a bug.

If you mean embedding chapters markers, this is implemented, you need to enable "Embed metadata" in preferences (but it should be enabled by default).

> What should we do about this issue?

Closing with "in-beta" label.
